name: vv-festim-report-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - jupyter-book
  - jupytext # necessary to open MyST files using BinderHub https://jupyterbook.org/en/stable/interactive/launchbuttons.html#launchbuttons-binder
  - sphinx-tags
  - numpy
  - matplotlib
  - sphinx
  - sympy
  - pandas
  - fenics
  - mpi4py<4
  - mpich
  - numpy=1.24
  - ipython=8.23
  - scipy
  - plotly
  - pip
  - pip:
    - festim==1.4
    - h_transport_materials
